version: 0.2

env:
  variables:
    LAMBDA: operations/scripts/lambda

phases:
  install:
    commands:
    - npm install jshint -g
  pre_build:
    commands:
    - cd $LAMBDA
    - jshint index.js --show-non-errors
    - npm install
  build:
    commands:
    - zip -r lambda.zip .
    - aws s3 cp "lambda.zip" "s3://$TEMPLATE_BUCKET/scripts/lambda.zip"
