version: 0.2

env:
  variables:
    OPS: operations

phases:
  install:
    commands:
    - pip install --upgrade pip
    - pip install yamllint
    - pip install demjson
  pre_build:
    commands:
    - yamllint .
    - |
      find . -type f -name '*.json' | while read file; do
        set -ex && jsonlint "$file"
      done
    - |
      find "$OPS" -type f -name "*.yml" | while read file; do
        aws s3 cp "$file" "s3://$TEMPLATE_BUCKET/Validation/$file"
        set -ex && aws cloudformation validate-template --template-url "s3://$TEMPLATE_BUCKET/Validation/$file"
      done
  build:
    commands:
    - echo "Copying $OPS files to S3"
    - |
      for file in $OPS; do
        aws s3 cp "$file" "s3://$TEMPLATE_BUCKET/$TEMPLATE_PREFIX/$file"
      done
    - echo "Building templates..."
artifacts:
  files:
  - 'operations/*'
  - 'templates/*'
