AWSTemplateFormatVersion: '2010-09-09'
Description: 'Group IAM permissions'
Parameters:

Resources:
  CodeCommitPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: "Policy for allowing access to codecommit"
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "codecommit:BatchGetRepositories"
          - "codecommit:Get*"
          - "codecommit:GitPull"
          - "codecommit:GitPush"
          - "codecommit:List*"
          - "codecommit:Put*"
          - "codecommit:Test*"
          - "codecommit:Update*"
          Resource:
          - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:*'
        - Effect: "Deny"
          Action:
          - "codecommit:GitPush"
          - "codecommit:DeleteBranch"
          - "codecommit:PutFile"
          - "codecommit:MergePullRequestByFastForward"
          Resource:
          - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:*'
          Condition:
            StringEqualsIfExists:
              "codecommit:References":
              - "refs/heads/master"
              - "refs/heads/release"
            Null:
              "codecommit:References": false


