AWSTemplateFormatVersion: '2010-09-09'
Description: 'Group IAM permissions'
Parameters:

Resources:
  ScoreboardsCodeCommitPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: "Policy for allowing access to scoreboards codecommit"
      Path: "/scoreboards/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "codecommit:BatchGetRepositories"
          - "codecommit:Get*"
          - "codecommit:GitPull"
          - "codecommit:GitPush"
          - "codecommit:List*"
          - "codecommit:Put*"
          - "codecommit:Test*"
          - "codecommit:Update*"
          Resource:
          - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sb-*'
          - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sb2-*'
  CodeCommitPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: "Policy for allowing access to scoreboards codecommit"
      Path: "/scoreboards/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "codecommit:BatchGetRepositories"
          - "codecommit:Get*"
          - "codecommit:GitPull"
          - "codecommit:GitPush"
          - "codecommit:List*"
          - "codecommit:Put*"
          - "codecommit:Test*"
          - "codecommit:Update*"
          Resource:
          - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sb-*'
          - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:sb2-*'



